### ISSUE TITLE
Questions about Equation (3) in the paper

### ISSUE THREAD

**Issue by StevenTang1998** [THUDM/InversePrompting#2]
This is a very innovative paper, which inspired me deeply.
I have some questions about Equation (3) in Section 4.2, and I feel that Equation (3) has some notation typos.
1. The paper metioned ``we apply inverse prompting Equation 2 for each sub-sentence and sum up their scores'', so I want to know how to split the sentence into sub-sentence?
2. What is the $n(c_g)$ in the denominator of the second item mean?

**Comment by xz-keg** [comment]
1:  A sentence is separated by sentence-ending punctuations like period or question mark, a sub-sentence is separated by any punctuations including comma.

2: It is the usual perplexity term (normalized by length) used in beam search.

**Comment by StevenTang1998** [comment]
I see. Thank you for your answer.
