### ISSUE TITLE
How to run the `generate_qa_desc.py` correctly ?

### ISSUE THREAD

**Issue by fangd123** [THUDM/InversePrompting#3]
I follow the `readme` to run `generate_qa_desc.py` but it reports error below:
```
FileNotFoundError: [Errno 2] No such file or directory: 'qa.jsonl'
```
So where is the `qa.jsonl` file ? I have found a lot file starting with "qa" but it seems no one was suitable for the `qa.jsonl`.

**Comment by xz-keg** [comment]
You need to create yourself. Put questions you wanna ask the model in that file.

**Comment by swaggy66** [comment]
how to run it in colab ？Or you run in other platform ？
