### ISSUE TITLE
复现不了结果

### ISSUE THREAD

**Issue by momo-journey** [THUDM/InversePrompting#5]
你好，我用以下数据、模型和代码，
数据：iPrompt/data/qa_human.jsonl里的question和desc字段
模型：[Chinese_Transformer_XL](https://github.com/THUDM/Chinese-Transformer-XL)
代码：iPrompt/chinese_ip/generate_qa_desc.py  代码没有改动

生成的answer和iPrompt/data/qa_ip.zip里的结果差别很大，后者流畅有逻辑，一些比较的例子：

我复现的结果：
{"question": "1812保险丝都是自恢复的吗,有不是自恢复的吗?", "desc": "", "answer": "1812的保险丝是耐压式,有自恢复保险丝,有的则是热熔型保险丝。目视明显。"}

qa_ip.zip里的结果：
{"question": "1812保险丝都是自恢复的吗,有不是自恢复的吗?", "desc": "", "answer": "1812自恢复保险丝主要有两种:1号VR150V型:此种保险丝兼具自恢复功能,可快速恢复好,自恢复时间10分钟以下。可以恢复外表观察或通电试验。"}

我复现的结果：
{"question": "武磊最新一次新冠病毒检测已转为阴性,你有什么想说的?", "desc": "", "answer": "如果武磊这次诊断的病毒转阴,我对他和他家人最为赞同。自疫情以来,武磊一直坚持在抗疫一线,和队员们一起,为国家的免疫力而战!此次武磊成功转阴,令人刮目相看!值得我们每一个人对他的支持和赞扬!"}

qa_ip.zip里的结果：
{"question": "武磊最新一次新冠病毒检测已转为阴性,你有什么想说的?", "desc": "", "answer": "首先祝贺武磊,期待他痊愈归来。这次新冠重症患者新冠抗体转阴,目前来看非常罕见,武磊也应该属于一类。因此客观来说,武磊已经具备对抗新冠病毒的免疫力。以上结论仅针对客观情况,不谈论主观,主观请勿来自我评判。另外武磊这次被录入样本库,是因为新冠样本是宝贵的,立即更新,对武磊较少有不利影响。且新冠会在感染者体内贮存较长时间,如果及时更新样本,能够更好保护武磊不受新冠感染。更新后,录入了武磊病毒样本,已经可以用来追溯新冠患者。希望武磊下次的复验结果能好。祝武磊早日康复,平安归来!2020年6月14日,武磊修订更新文件,删除了自己19日诊断为新冠的陈述。"}

我复现的结果：
{"question": "遇到一个难题,西门子洗碗机8套和13套到底选哪个?", "desc": "", "answer": "13套洗碗机升级为8套,外观时尚,智能联动和闲置返还功能。西门子8套洗碗机的出水更加强劲,洗涤效果更出色。关键是价格上也会更实惠些,大概在4000元左右。"}

qa_ip.zip里的结果：
{"question": "遇到一个难题,西门子洗碗机8套和13套到底选哪个?", "desc": "", "answer": "一般人都使用8套洗碗机,觉得13套的太贵,容量也大,感觉没有8套实用的,就经常拿这个问题吐槽西门子,其实13套容量是大了,和8套比起来,单台洗碗机使用率还是高很多的,只是13套安装贵,很麻烦,所以大家还是买8套吧,洗碗机用13套的结果,就是每天洗碗的时候,那任务量是很大。西门子8套是137L,比13套还多出12L,基本上用到6套,洗碗机就满了,而西门子13套台深为539mm,比8套多出来290mm,洗碗机放不倒,现在洗碗机可以放得下8套台面,但是放不下13套,所以买8套就好。"}

求教问会是什么问题？谢谢！

**Comment by xz-keg** [comment]
代码里设置生成的时候会生成20个长短各异的答案，然后选择按句平均inverse prompting score最优的答案输出。这些答案的inverse prompting score一般很接近，所以输出哪一个答案随机性很大。

由于种子是随机的，反复运行的结果会有很大差别。

如果想要固定让他生成长一些的答案，可以通过在代码里设置（如在481行之前添加一句 if i>10:），排除掉比较短的答案。

或者也可以直接去看676行的output_string，里面有模型生成的长短各异的所有备选答案和模型对此答案的参考评分。
